lib/pitera_web/router.ex
defmodule PiteraWeb.Router do
  use PiteraWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :pitera

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: PiteraWeb.AuthErrorHandler
  end

  pipeline :protected_browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    #plug :protect_from_forgery
    plug Pow.Plug.RequireAuthenticated,
      error_handler: PiteraWeb.AuthErrorHandler
    plug :put_secure_browser_headers
    plug PiteraWeb.Plugs.SetCurrentUser
  end

  scope "/" do
    pipe_through :browser
    pow_extension_routes()
  end

  scope "/" do
    pipe_through :protected_browser
    # Add public routes below
  end

  scope "/", PiteraWeb do
    pipe_through :browser
    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    # Add public routes below
  end

  scope "/", PiteraWeb do
    pipe_through :protected_browser
    # Add protected routes below
    delete "/logout", SessionController, :delete, as: :logout

    resources "/materials", MaterialController, except: [:new, :edit]
    get "/materials/:id/simplified", MaterialController, :show_simplified
    get "/materials_properties", MaterialController, :get_properties_list
    get "/materials/:id/stocks", MaterialController, :get_stock_list
    get "/materials/stocks/:id", MaterialController, :get_stock_by_id
    post "/materials/:id/stocks/new", MaterialController, :create_stock
    put "/materials/:material_id/stocks/:id", MaterialController, :update_stock
    delete "/materials/stocks/:id", MaterialController, :delete_stock
    get "/*catch_all", PageController, :index
  end
end

lib/pitera_web/controllers/session_controller.ex
defmodule PiteraWeb.SessionController do
  use PiteraWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: "/")

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])
        conn
        |> put_flash(:info, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    {:ok, conn} = Pow.Plug.delete(conn)
    redirect(conn, to: "/")
  end
end

lib/pitera_web/views/session_view.ex
defmodule PiteraWeb.SessionView do
  use PiteraWeb, :view
end

lib/pitera_web/templates/session/new.html.eex
<h1>Sign in</h1>

<%= form_for @changeset, "/login", [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset) %>
  <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>

  <%= label f, :password %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>

  <div>
    <%= submit "Sign in" %>
  </div>
  <%= label f, :persistent_session, "Remember me" %>
  <%= checkbox f, :persistent_session %>
<% end %>


<span><%= link "Register", to: Routes.signup_path(@conn, :new) %></span>
<span><%= link("Reset password", to: Routes.pow_reset_password_reset_password_path(@conn, :new)) %></span>