lib/pitera_web/router.ex
defmodule PiteraWeb.Router do
  use PiteraWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :pitera

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: PiteraWeb.AuthErrorHandler
  end

  pipeline :protected_browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    #plug :protect_from_forgery
    plug Pow.Plug.RequireAuthenticated,
      error_handler: PiteraWeb.AuthErrorHandler
    plug :put_secure_browser_headers
    plug PiteraWeb.Plugs.SetCurrentUser
  end

  scope "/" do
    pipe_through :browser
    pow_extension_routes()
  end

  scope "/" do
    pipe_through :protected_browser
    # Add public routes below
  end

  scope "/", PiteraWeb do
    pipe_through :browser
    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    # Add public routes below
  end

  scope "/", PiteraWeb do
    pipe_through :protected_browser
    # Add protected routes below
    delete "/logout", SessionController, :delete, as: :logout

    resources "/materials", MaterialController, except: [:new, :edit]
    get "/materials/:id/simplified", MaterialController, :show_simplified
    get "/materials_properties", MaterialController, :get_properties_list
    get "/materials/:id/stocks", MaterialController, :get_stock_list
    get "/materials/stocks/:id", MaterialController, :get_stock_by_id
    post "/materials/:id/stocks/new", MaterialController, :create_stock
    put "/materials/:material_id/stocks/:id", MaterialController, :update_stock
    delete "/materials/stocks/:id", MaterialController, :delete_stock
    get "/*catch_all", PageController, :index
  end
end

lib/pitera_web/views/pow_reset_password/mailer_view.ex
defmodule PiteraWeb.PowResetPassword.MailerView do
  use PiteraWeb, :mailer_view

  def subject(:reset_password, _assigns), do: "Reset password link"
end

lib/pitera_web/views/pow_reset_password/reset_password_view.ex
defmodule PiteraWeb.PowResetPassword.ResetPasswordView do
  use PiteraWeb, :view
end

lib/pitera_web/templates/pow_reset_password/reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>

  <%= label f, :confirm_password %>
  <%= password_input f, :confirm_password %>
  <%= error_tag f, :confirm_password %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>


<span><%= link "Sign in", to: Routes.login_path(@conn, :new) %></span>

lib/pitera_web/templates/pow_reset_password/reset_password/new.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>